### ISSUE TITLE
Verbindung testen nicht möglich mit Influx 2.x Datenbank

### ISSUE THREAD

**Issue by Feuer-sturm** [ioBroker/ioBroker.influxdb#146]
Admin 5.1.24
Influxdb Adapter 2.1.1
Influx Datenbank 2.x

Wenn in der Instanz der Button "Verbindung testen" betätigt wird erscheint nicht die Meldung "OK" sondern folgene Warnungen sind im Log enthalten:

```
15 Aug 2021 23:15:33.258
influxdb.0 (9642) TypeError: Cannot read property 'port' of undefined at testConnection (/opt/iobroker/node_modules/iobroker.influxdb/main.js:350:59) at processMessage (/opt/iobroker/node_modules/iobroker.influxdb/main.js:446:9) at Adapter.<anonymous> (/opt/iobroker/node_modules/iobroker.influxdb/main.js:164:34) at Adapter.emit (events.js:314:20) at Adapter.EventEmitter.emit (domain.js:483:12) at change (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:5634:34) at Immediate._onImmediate (/opt/iobroker/node_modules/@iobroker/db-states-redis/lib/states/statesInRedisClient.js:232:37) at processImmediate (internal/timers.js:461:21)
15 Aug 2021 23:15:33.237
influxdb.0 (9642) States system pmessage io.messagebox.system.adapter.influxdb.0 {"command":"test","message":"{\"config\": {\"dbversion\": \"2.x\", \"protocol\": \"http\", \"port\": \"8086\", \"host\": \"192.168.178.101\", \"user\": \"iobroker\", \"organization\": \"iobroker\", \"dbname\": \"iobroker\", \"password\": \"K@E(xHX}4DT-[cT;*\f\", \"token\": \"xxx"}","from":"system.adapter.admin.0","callback":{"message":"{\"config\": {\"dbversion\": \"2.x\", \"protocol\": \"http\", \"port\": \"8086\", \"host\": \"192.168.178.101\", \"user\": \"iobroker\", \"organization\": \"iobroker\", \"dbname\": \"iobroker\", \"password\": \"K@E(xHX}4DT-[cT;*\f\", \"token\": \"xxx\,"id":26,"ack":false,"time":1629062133230},"_id":91647056} Cannot read property 'port' of undefined
```

**Comment by Apollon77** [comment]
@Excodibur I think we should add logging zto see what really comes in, seems that "message" is a josn stringified content instead of an object?!

**Comment by Excodibur** [comment]
@Apollon77 You mean a debug log line here? https://github.com/ioBroker/ioBroker.influxdb/blob/43ce3a2cfbd0ae3545ca9d0cc9690a2147db562e/main.js#L350

**Comment by Feuer-sturm** [comment]
I Updates from a github Version of the influx Adapter to Version 2.1.1
Perhaps this Information is helpful.
I can delete the complete Adapter and install a fresh version and have a look if this is working.

**Comment by Apollon77** [comment]
> @Apollon77 You mean a debug log line here? 

Yes , just log "JSON.stringify(msg.message)" ... or better whole "msg"?

**Comment by MMeinhardt1** [comment]
Hi, i have the same problem with influx v1.6.4 and adapter v2.1.1. With the github v1.9.5 with influx v2 support the connection test was ok.



```
2021-08-16 20:10:19.906 - warn: influxdb.0 (13168) States system pmessage io.messagebox.system.adapter.influxdb.0 {"command":"test","message":"{\"config\": {\"dbversion\": \"1.x\", \"protocol\": \"http\", \"port\": \"8086\", \"host\": \"localhost\", \"user\": \"iobroker\", \"organization\": \"\", \"dbname\": \"iobroker\", \"password\": \"V\u0002\u000b\u0000YU\", \"token\": \"\"}}","from":"system.adapter.admin.0","callback":{"message":"{\"config\": {\"dbversion\": \"1.x\", \"protocol\": \"http\", \"port\": \"8086\", \"host\": \"localhost\", \"user\": \"iobroker\", \"organization\": \"\", \"dbname\": \"iobroker\", \"password\": \"V\u0002\u000b\u0000YU\", \"token\": \"\"}}","id":54,"ack":false,"time":1629137419901},"_id":84692604} Cannot read property 'port' of undefined
2021-08-16 20:10:19.927 - warn: influxdb.0 (13168) TypeError: Cannot read property 'port' of undefined
```

**Comment by Excodibur** [comment]
Please install the latest version from Github an check again, with DEBUG-logging enabled. There issue it self was not fixed, but now we should be able to see the contents of the msg-object in the logs to analyze it further.

**Comment by Feuer-sturm** [comment]
Influx Adapter: Current version from github

@Excodibur Here is the new debug log. The string after  `\"password\"` looks strange
What is this for a password?



```
influxdb.0
	2021-08-23 22:03:37.065	debug	PING OK
influxdb.0
	2021-08-23 22:03:36.764	warn	TypeError: Cannot read property 'port' of undefined at testConnection (/opt/iobroker/node_modules/iobroker.influxdb/main.js:376:59) at processMessage (/opt/iobroker/node_modules/iobroker.influxdb/main.js:472:9) at Adapter.<anonymous> (/opt/iobroker/node_modules/iobroker.influxdb/main.js:164:34) at Adapter.emit (events.js:314:20) at Adapter.EventEmitter.emit (domain.js:483:12) at change (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:5634:34) at Immediate._onImmediate (/opt/iobroker/node_modules/@iobroker/db-states-redis/lib/states/statesInRedisClient.js:232:37) at processImmediate (internal/timers.js:461:21)
influxdb.0
	2021-08-23 22:03:36.744	warn	States system pmessage io.messagebox.system.adapter.influxdb.0 {"command":"test","message":"{\"config\": {\"dbversion\": \"2.x\", \"protocol\": \"http\", \"port\": \"8086\", \"host\": \"192.168.178.101\", \"user\": \"iobroker\", \"organization\": \"iobroker\", \"dbname\": \"iobroker\", \"password\": \"K@E(xHX}4DT-[cT;*\f\", \"token\": \"AOxxx==\"}}","from":"system.adapter.admin.0","callback":{"message":"{\"config\": {\"dbversion\": \"2.x\", \"protocol\": \"http\", \"port\": \"8086\", \"host\": \"192.168.178.101\", \"user\": \"iobroker\", \"organization\": \"iobroker\", \"dbname\": \"iobroker\", \"password\": \"K@E(xHX}4DT-[cT;*\f\", \"token\": \"AOxxx==\"}}","id":37,"ack":false,"time":1629749016736},"_id":13226101} Cannot read property 'port' of undefined
influxdb.0
	2021-08-23 22:03:36.743	debug	testConnection msg-object: {"command":"test","message":"{\"config\": {\"dbversion\": \"2.x\", \"protocol\": \"http\", \"port\": \"8086\", \"host\": \"192.168.178.101\", \"user\": \"iobroker\", \"organization\": \"iobroker\", \"dbname\": \"iobroker\", \"password\": \"K@E(xHX}4DT-[cT;*\f\", \"token\": \"AOxxx==\"}}","from":"system.adapter.admin.0","callback":{"message":"{\"config\": {\"dbversion\": \"2.x\", \"protocol\": \"http\", \"port\": \"8086\", \"host\": \"192.168.178.101\", \"user\": \"iobroker\", \"organization\": \"iobroker\", \"dbname\": \"iobroker\", \"password\": \"K@E(xHX}4DT-[cT;*\f\", \"token\": \"AOxxx==\"}}","id":37,"ack":false,"time":1629749016736},"_id":13226101}
influxdb.0
	2021-08-23 22:03:36.740	debug	Incoming message test from system.adapter.admin.0
```

**Comment by Apollon77** [comment]
@Excodibur looks like if the message is "double encoded" ... maybe it is sent incorrectly by admin?

**Comment by Excodibur** [comment]
@Feuer-sturm The output is weird on multiple levels:

1. As Apollon guessed, the message-object should not contain an escaped config-object
2. The password/token fields seem to contain an encrypted value, but at the time the adapter logs the object, they should be decrypted already. FYI although you can switch between Influx 1 & 2 configuration, the credentials are still stored in the same config object, so you might see here a Influx 1 password, if configured, in parallel to you Influx 2 token.

The problem I have, is that neither of those two things works wrongly on my side currently. It works fine in old, and new GUI of Admin 5. Which GUI are you using?

I am using the following adapter versions:
- Admin 5.1.25 (but looking at the changes it should make no difference)
- JS-Controller 3.3.15 (please check yours)

Also which Browser (+version) are you using for your tests?

**Comment by Feuer-sturm** [comment]
@Excodibur 
I have a multi-host system for testing with the following configuration

ioBroker Master
Admin 5.1.25 with react UI
js-controller 3.3.15
Influx Adapter

ioBroker Slave
Admin 5.1.25
js-controller 3.3.15

Influx Database
Is running in a seperate proxmox LXC container
proxmox@DatenbankenTest:~$ influx version
Influx CLI 2.0.7 (git: 2a45f0c037) build_date: 2021-06-04T19:17:40Z

Browser for testing
- Firefox 91.0.1 (64-Bit)
- Chrome 92.0.4515.159 (Offizieller Build) (64-Bit)

**Comment by Apollon77** [comment]
@Feuer-sturm Can you please test this with the "old admin ui" please ... is it working there?

**Comment by Excodibur** [comment]
@Feuer-sturm Please also provide some information regarding the Node-Version, you use.

**Comment by RkcCorian** [comment]
I tested this today and it was working with influxDB2
