### ISSUE TITLE
TypeError: Cannot read property 'startsWith' of undefined

### ISSUE THREAD

**Issue by Anzic23** [ioBroker/ioBroker.influxdb#257]
**Describe the bug**  
The adapter starts, starts reading objects for logging and stops with an error - Terminated (UNCAUGHT_EXCEPTION): Without reason

**Screenshots & Logfiles**  
```
2022-05-12 13:39:47.562  - [33mwarn[39m: influxdb.0 (17603) Terminated (UNCAUGHT_EXCEPTION): Without reason
2022-05-12 13:39:47.976  - [33mwarn[39m: influxdb.0 (17603) Alias alias.0.Спальня.miLamp1.color has no target 12
2022-05-12 13:39:48.182  - [31merror[39m: host.iobroker Caught by controller[0]: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
2022-05-12 13:39:48.182  - [31merror[39m: host.iobroker Caught by controller[1]: TypeError: Cannot read property 'startsWith' of undefined
2022-05-12 13:39:48.183  - [31merror[39m: host.iobroker Caught by controller[1]:     at connect (/opt/iobroker/node_modules/iobroker.influxdb/main.js:298:29)
2022-05-12 13:39:48.183  - [31merror[39m: host.iobroker Caught by controller[1]:     at main (/opt/iobroker/node_modules/iobroker.influxdb/main.js:830:5)
2022-05-12 13:39:48.183  - [31merror[39m: host.iobroker Caught by controller[1]:     at Adapter.<anonymous> (/opt/iobroker/node_modules/iobroker.influxdb/main.js:228:31)
2022-05-12 13:39:48.183  - [31merror[39m: host.iobroker Caught by controller[1]:     at Adapter.emit (events.js:400:28)
2022-05-12 13:39:48.183  - [31merror[39m: host.iobroker Caught by controller[1]:     at Adapter.emit (domain.js:475:12)
2022-05-12 13:39:48.183  - [31merror[39m: host.iobroker Caught by controller[1]:     at /opt/iobroker/node_modules/@iobroker/js-controller-adapter/src/lib/adapter/adapter.js:9132:26
2022-05-12 13:39:48.184  - [31merror[39m: host.iobroker instance system.adapter.influxdb.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
2022-05-12 13:39:48.184  - [32minfo[39m: host.iobroker Restart adapter system.adapter.influxdb.0 because enabled
2022-05-12 13:39:52.589  - [32minfo[39m: mihome-airpurifier.0 (8331) State value to set for "mihome-airpurifier.0.info.temperature" has to be type "number" but received type "string" 
2022-05-12 13:40:18.406  - [32minfo[39m: host.iobroker instance system.adapter.influxdb.0 started with pid 17715
2022-05-12 13:40:20.122  - [32minfo[39m: influxdb.0 (17715) starting. Version 3.0.1 in /opt/iobroker/node_modules/iobroker.influxdb, node: v14.19.2, js-controller: 4.0.23
2022-05-12 13:40:20.166  - [32minfo[39m: influxdb.0 (17715) No stored data from last exit found
2022-05-12 13:40:20.169  - [31merror[39m: influxdb.0 (17715) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2022-05-12 13:40:20.169  - [31merror[39m: influxdb.0 (17715) unhandled promise rejection: Cannot read property 'startsWith' of undefined
2022-05-12 13:40:20.297  - [31merror[39m: influxdb.0 (17715) TypeError: Cannot read property 'startsWith' of undefined
    at connect (/opt/iobroker/node_modules/iobroker.influxdb/main.js:298:29)
    at main (/opt/iobroker/node_modules/iobroker.influxdb/main.js:830:5)
    at Adapter.<anonymous> (/opt/iobroker/node_modules/iobroker.influxdb/main.js:228:31)
    at Adapter.emit (events.js:400:28)
    at Adapter.emit (domain.js:475:12)
    at /opt/iobroker/node_modules/@iobroker/js-controller-adapter/src/lib/adapter/adapter.js:9132:26
2022-05-12 13:40:20.298  - [31merror[39m: influxdb.0 (17715) Cannot read property 'startsWith' of undefined
2022-05-12 13:40:20.448  - [32minfo[39m: influxdb.0 (17715) enabled logging of 0_userdata.0.Garag.car.gps-location, Alias=false, 1 points now activated
2022-05-12 13:40:20.448  - [32minfo[39m: influxdb.0 (17715) enabled logging of 0_userdata.0.Garag.car.place, Alias=false, 2 points now activated
2022-05-12 13:40:20.449  - [32minfo[39m: influxdb.0 (17715) enabled logging of 0_userdata.0.Garag.nomer, Alias=false, 3 points now activated
2022-05-12 13:40:20.449  - [32minfo[39m: influxdb.0 (17715) enabled logging of 0_userdata.0.Server-room.gaz, Alias=false, 4 points now activated
2022-05-12 13:40:20.449  - [32minfo[39m: influxdb.0 (17715) enabled logging of 0_userdata.0.System.Alive.Fonar, Alias=false, 5 points now activated
2022-05-12 13:40:20.450  - [32minfo[39m: influxdb.0 (17715) enabled logging of 0_userdata.0.System.Alive.Sarai, Alias=false, 6 points now activated
2022-05-12 13:40:20.450  - [32minfo[39m: influxdb.0 (17715) enabled logging of 0_userdata.0.System.Alive.Svet_vhod, Alias=false, 7 points now activated
2022-05-12 13:40:20.450  - [32minfo[39m: influxdb.0 (17715) enabled logging of 0_userdata.0.System.Alive.garage, Alias=false, 8 points now activated
2022-05-12 13:40:20.451  - [32minfo[39m: influxdb.0 (17715) enabled logging of 0_userdata.0.System.Alive.gost_vorota, Alias=false, 9 points now activated
2022-05-12 13:40:20.451  - [32minfo[39m: influxdb.0 (17715) enabled logging of 0_userdata.0.System.Alive.nexus4, Alias=false, 10 points now activated
2022-05-12 13:40:20.451  - [32minfo[39m: influxdb.0 (17715) enabled logging of 0_userdata.0.System.Alive.prihozhaya, Alias=false, 11 points now activated
___________
many lines with objects for logging
___________
2022-05-12 13:40:20.632  - [32minfo[39m: influxdb.0 (17715) enabled logging of zwave.0.NODE58.ZWAVE_PLUS_INFO.ZWave+_Version, Alias=false, 726 points now activated
2022-05-12 13:40:20.632  - [32minfo[39m: influxdb.0 (17715) enabled logging of zwave.0.NODE58.alive, Alias=false, 727 points now activated
2022-05-12 13:40:20.632  - [32minfo[39m: influxdb.0 (17715) enabled logging of zwave.0.NODE58.event, Alias=false, 728 points now activated
2022-05-12 13:40:20.632  - [32minfo[39m: influxdb.0 (17715) enabled logging of zwave.0.NODE58.ready, Alias=false, 729 points now activated
2022-05-12 13:40:20.633  - [32minfo[39m: influxdb.0 (17715) enabled logging of zwave.0.NODE58.sleep, Alias=false, 730 points now activated
2022-05-12 13:40:20.633  - [32minfo[39m: influxdb.0 (17715) enabled logging of zwave.0.NODE9.alive, Alias=false, 731 points now activated
2022-05-12 13:40:20.633  - [32minfo[39m: influxdb.0 (17715) enabled logging of zwave2.0.Node_011.status, Alias=false, 732 points now activated
2022-05-12 13:40:20.633  - [32minfo[39m: influxdb.0 (17715) enabled logging of zwave2.0.Node_012.status, Alias=false, 733 points now activated
2022-05-12 13:40:20.633  - [32minfo[39m: influxdb.0 (17715) enabled logging of zwave2.0.Node_013.Thermostat_Setpoint.setpoint_heating, Alias=false, 734 points now activated
2022-05-12 13:40:20.634  - [32minfo[39m: influxdb.0 (17715) enabled logging of zwave2.0.Node_013.ready, Alias=false, 735 points now activated
2022-05-12 13:40:20.634  - [32minfo[39m: influxdb.0 (17715) enabled logging of zwave2.0.Node_017.Thermostat_Mode.mode, Alias=false, 736 points now activated
2022-05-12 13:40:20.634  - [32minfo[39m: influxdb.0 (17715) enabled logging of zwave2.0.Node_028.Configuration.operationMode, Alias=false, 737 points now activated
2022-05-12 13:40:20.634  - [32minfo[39m: influxdb.0 (17715) enabled logging of zwave2.0.Node_049.Alarm_Sensor.state_5, Alias=false, 738 points now activated
2022-05-12 13:40:20.634  - [32minfo[39m: influxdb.0 (17715) enabled logging of zwave2.0.Node_052.Alarm_Sensor.state_0, Alias=false, 739 points now activated
2022-05-12 13:40:20.634  - [32minfo[39m: influxdb.0 (17715) enabled logging of zwave2.0.Node_052.Alarm_Sensor.state_5, Alias=false, 740 points now activated
2022-05-12 13:40:20.635  - [32minfo[39m: influxdb.0 (17715) enabled logging of zwave2.0.Node_056.Multilevel_Switch.up, Alias=false, 741 points now activated
2022-05-12 13:40:20.635  - [32minfo[39m: influxdb.0 (17715) enabled logging of zwave2.0.Node_058.Notification.homeSecurity_coverStatus, Alias=false, 742 points now activated
2022-05-12 13:40:20.635  - [32minfo[39m: influxdb.0 (17715) enabled logging of zwave2.0.Node_058.Notification.waterAlarm_sensorStatus, Alias=false, 743 points now activated
2022-05-12 13:40:20.635  - [32minfo[39m: influxdb.0 (17715) enabled logging of zwave2.0.Node_061.Central_Scene.scene_001, Alias=false, 744 points now activated
2022-05-12 13:40:20.635  - [32minfo[39m: influxdb.0 (17715) enabled logging of zwave2.0.Node_061.Central_Scene.scene_002, Alias=false, 745 points now activated
2022-05-12 13:40:20.635  - [32minfo[39m: influxdb.0 (17715) enabled logging of zwave2.0.Node_061.Central_Scene.scene_003, Alias=false, 746 points now activated
2022-05-12 13:40:20.636  - [32minfo[39m: influxdb.0 (17715) enabled logging of zwave2.0.Node_061.Central_Scene.scene_004, Alias=false, 747 points now activated
2022-05-12 13:40:21.607  - [33mwarn[39m: influxdb.0 (17715) Terminated (UNCAUGHT_EXCEPTION): Without reason
2022-05-12 13:40:22.070  - [33mwarn[39m: influxdb.0 (17715) Alias alias.0.Спальня.miLamp1.color has no target 12
2022-05-12 13:40:22.251  - [31merror[39m: host.iobroker Caught by controller[0]: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
2022-05-12 13:40:22.251  - [31merror[39m: host.iobroker Caught by controller[0]: TypeError: Cannot read property 'startsWith' of undefined
2022-05-12 13:40:22.251  - [31merror[39m: host.iobroker Caught by controller[0]:     at connect (/opt/iobroker/node_modules/iobroker.influxdb/main.js:298:29)
2022-05-12 13:40:22.252  - [31merror[39m: host.iobroker Caught by controller[0]:     at main (/opt/iobroker/node_modules/iobroker.influxdb/main.js:830:5)
2022-05-12 13:40:22.252  - [31merror[39m: host.iobroker Caught by controller[0]:     at Adapter.<anonymous> (/opt/iobroker/node_modules/iobroker.influxdb/main.js:228:31)
2022-05-12 13:40:22.252  - [31merror[39m: host.iobroker Caught by controller[0]:     at Adapter.emit (events.js:400:28)
2022-05-12 13:40:22.252  - [31merror[39m: host.iobroker Caught by controller[0]:     at Adapter.emit (domain.js:475:12)
2022-05-12 13:40:22.252  - [31merror[39m: host.iobroker Caught by controller[0]:     at /opt/iobroker/node_modules/@iobroker/js-controller-adapter/src/lib/adapter/adapter.js:9132:26
2022-05-12 13:40:22.253  - [31merror[39m: host.iobroker instance system.adapter.influxdb.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
```

**Versions:**  
 - Adapter version: 3.0.1
 - JS-Controller version: 4.0.23
 - Node version: v14.19.2
 - Operating system: docker 6.1.0

**Comment by Apollon77** [comment]
Interesting ... can you please try if an "iob upload influxdb" fixes this for you?

I will also release 3.0.2 soon to address this, but as ssaid should not happen at all

**Comment by Anzic23** [comment]
on version 2.6.3 everything is fine. there is no such error. I will try iob upload influxdb on version 3.0.1

**Comment by Apollon77** [comment]
3.0 added a new paraeter but normally it should initialize it with the default value from io-package ... strange ... alternatively ... 3.0.2 on it's way too (or GitHub)

**Comment by Anzic23** [comment]
strange, when upgrading from 2.6.3 to 3.0.1, files were uploadet and the adapter start work

**Comment by Apollon77** [comment]
Ok, so somethign was strange on initial update? ... wtf :-))

but 3.0.2 make sure it is not happening at all

**Comment by Anzic23** [comment]
I do not know :)
glad to hear it was helpful ;)

**Comment by Anzic23** [comment]
Now I have another error:
```
influxdb.0 | 2022-05-31 11:09:38.826 | warn | TypeError: Cannot read property 'port' of undefined at testConnection (/opt/iobroker/node_modules/iobroker.influxdb/main.js:447:59) at processMessage (/opt/iobroker/node_modules/iobroker.influxdb/main.js:563:9) at Adapter.<anonymous> (/opt/iobroker/node_modules/iobroker.influxdb/main.js:232:34) at Adapter.emit (events.js:400:28) at Adapter.emit (domain.js:475:12) at change (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/src/lib/adapter/adapter.js:5824:34) at Immediate._onImmediate (/opt/iobroker/node_modules/@iobroker/db-states-redis/lib/states/statesInRedisClient.js:324:37) at processImmediate (internal/timers.js:464:21)
-- | -- | -- | --
influxdb.0 | 2022-05-31 11:09:38.624 | warn | States system pmessage messagebox.system.adapter.influxdb.0 {"command":"test","message":"{\"config\": {\"dbversion\": \"2.x\", \"protocol\": \"http\", \"port\": \"8086\", \"host\": \"influxdb\", \"user\": \"admin\", \"organization\": \"Anzor\", \"dbname\": \"iobroker/global\", \"requestTimeout\": \"300000\", \"validateSSL\": true, \"password\": \"V\u0002][]\", \"token\": \"bkAy9vDgOU-8X_2pzM_orDnDgli7VArkjOBrOZuE_U0OCNFDYfr6hACKOqczh2jSuMNqH-cFmcEB-lnVnzRczg==\", \"path\": \"\"}}","from":"system.adapter.admin.0","callback":{"message":"{\"config\": {\"dbversion\": \"2.x\", \"protocol\": \"http\", \"port\": \"8086\", \"host\": \"influxdb\", \"user\": \"admin\", \"organization\": \"Anzor\", \"dbname\": \"iobroker/global\", \"requestTimeout\": \"300000\", \"validateSSL\": true, \"password\": \"V\u0002][]\", \"token\": \"bkAy9vDgOU-8X_2pzM_orDnDgli7VArkjOBrOZuE_U0OCNFDYfr6hACKOqczh2jSuMNqH-cFmcEB-lnVnzRczg==\", \"path\": \"\"}}","id":119,"ack":false,"time":1653984578622},"_id":94415979} Cannot read property 'port' of undefined
```
Appears when I click the "test connection" button

**Comment by Apollon77** [comment]
I will checjk, but in future please open a new issue for  a new error :-)

**Comment by Anzic23** [comment]
> I will checjk, but in future please open a new issue for a new error :-)

ок )

**Comment by Apollon77** [comment]
and BTW: Which adapter version?

**Comment by Anzic23** [comment]
> and BTW: Which adapter version?

3.1.0

**Comment by Anzic23** [comment]
2022-05-31 11:37:30.848  - [34mdebug[39m: influxdb.0 (27210) Write Point: system.adapter.influxdb.0.memHeapTotal values:{"value":95.11,"time":"2022-05-31T08:37:30.333Z","from":"system.adapter.influxdb.0","q":0,"ack":true} options: null
2022-05-31 11:37:30.849  - [34mdebug[39m: influxdb.0 (27210) Write Point: system.adapter.influxdb.0.memHeapUsed values:{"value":73.37,"time":"2022-05-31T08:37:30.333Z","from":"system.adapter.influxdb.0","q":0,"ack":true} options: null
2022-05-31 11:37:31.128  - [34mdebug[39m: influxdb.0 (27210) Point written to iobroker/global
2022-05-31 11:37:31.132  - [34mdebug[39m: influxdb.0 (27210) Incoming message test from system.adapter.admin.0
2022-05-31 11:37:31.134  - [34mdebug[39m: influxdb.0 (27210) testConnection msg-object: {"command":"test","message":"{\"config\": {\"dbversion\": \"2.x\", \"protocol\": \"http\", \"port\": \"8086\", \"host\": \"influxdb\", \"user\": \"admin\", \"organization\": \"Anzor\", \"dbname\": \"iobroker/global\", \"requestTimeout\": \"300000\", \"validateSSL\": true, \"password\": \"V\u0002][]\", \"token\": \"bk--czg==\", \"path\": \"\"}}","from":"system.adapter.admin.0","callback":{"message":"{\"config\": {\"dbversion\": \"2.x\", \"protocol\": \"http\", \"port\": \"8086\", \"host\": \"influxdb\", \"user\": \"admin\", \"organization\": \"Anzor\", \"dbname\": \"iobroker/global\", \"requestTimeout\": \"300000\", \"validateSSL\": true, \"password\": \"V\u0002][]\", \"token\": \"b--Rczg==\", \"path\": \"\"}}","id":120,"ack":false,"time":1653986251130},"_id":94415981}
2022-05-31 11:37:31.134  - [33mwarn[39m: influxdb.0 (27210) States system pmessage messagebox.system.adapter.influxdb.0 {"command":"test","message":"{\"config\": {\"dbversion\": \"2.x\", \"protocol\": \"http\", \"port\": \"8086\", \"host\": \"influxdb\", \"user\": \"admin\", \"organization\": \"Anzor\", \"dbname\": \"iobroker/global\", \"requestTimeout\": \"300000\", \"validateSSL\": true, \"password\": \"V\u0002][]\", \"token\": \"bk--Rczg==\", \"path\": \"\"}}","from":"system.adapter.admin.0","callback":{"message":"{\"config\": {\"dbversion\": \"2.x\", \"protocol\": \"http\", \"port\": \"8086\", \"host\": \"influxdb\", \"user\": \"admin\", \"organization\": \"Anzor\", \"dbname\": \"iobroker/global\", \"requestTimeout\": \"300000\", \"validateSSL\": true, \"password\": \"V\u0002][]\", \"token\": \"b--zRczg==\", \"path\": \"\"}}","id":120,"ack":false,"time":1653986251130},"_id":94415981} Cannot read property 'port' of undefined
2022-05-31 11:37:31.412  - [33mwarn[39m: influxdb.0 (27210) TypeError: Cannot read property 'port' of undefined
    at testConnection (/opt/iobroker/node_modules/iobroker.influxdb/main.js:447:59)
    at processMessage (/opt/iobroker/node_modules/iobroker.influxdb/main.js:563:9)
    at Adapter.<anonymous> (/opt/iobroker/node_modules/iobroker.influxdb/main.js:232:34)
    at Adapter.emit (events.js:400:28)
    at Adapter.emit (domain.js:475:12)
    at change (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/src/lib/adapter/adapter.js:5824:34)
    at Immediate._onImmediate (/opt/iobroker/node_modules/@iobroker/db-states-redis/lib/states/statesInRedisClient.js:324:37)
    at processImmediate (internal/timers.js:464:21)
2022-05-31 11:37:31.674  - [34mdebug[39m: influxdb.0 (27210) Point written to iobroker/global
2022-05-31 11:37:31.674  - [34mdebug[39m: influxdb.0 (27210) Point written to iobroker/global
2022-05-31 11:37:31.872  - [34mdebug[39m: influxdb.0 (27210) Write Point: mqtt.3.ESP_Easy_DRAGON.Davlenie.Analog values:{"value":1.31,"time":"2022-05-31T08:37:26.869Z","from":"system.adapter.mqtt.3","q":0,"ack":true} options: null
2022-05-31 11:37:31.876  - [34mdebug[39m: influxdb.0 (27210) Write Point: linkeddevices.0.server-room.davlenie values:{"value":1.31,"time":"2022-05-31T08:37:26.880Z","from":"system.adapter.linkeddevices.0","q":0,"ack":true} options: null
2022-05-31 11:37:32.055  - [34mdebug[39m: influxdb.0 (27210) Point written to iobroker/global
2022-05-31 11:37:32.100  - [34mdebug[39m: influxdb.0 (27210) PING OK
2022-05-31 11:37:32.166  - [34mdebug[39m: influxdb.0 (27210) Point written to iobroker/global
2022-05-31 11:37:32.373  - [34mdebug[39m: influxdb.0 (27210) Write Point: mqtt.3.ESP_Easy_DRAGON.Davlenie.Analog values:{"value":1.27,"time":"2022-05-31T08:37:31.871Z","from":"system.adapter.mqtt.3","q":0,"ack":true} options: null
2022-05-31 11:37:32.377  - [34mdebug[39m: influxdb.0 (27210) Write Point: linkeddevices.0.server-room.davlenie values:{"value":1.27,"time":"2022-05-31T08:37:31.875Z","from":"system.adapter.linkeddevices.0","q":0,"ack":true} options: null
2022-05-31 11:37:32.480  - [34mdebug[39m: influxdb.0 (27210) Point written to iobroker/global
2022-05-31 11:37:32.522  - [34mdebug[39m: influxdb.0 (27210) Point written to iobroker/global
2022-05-31 11:37:32.848  - [34mdebug[39m: influxdb.0 (27210) Write Point: mercury.0.1768243.MainsParameters.powerTotal values:{"value":3117.52,"time":"2022-05-31T08:37:32.346Z","from":"system.adapter.mercury.0","q":0,"ack":true} options: null
2022-05-31 11:37:32.853  - [34mdebug[39m: influxdb.0 (27210) Write Point: mercury.0.1768243.MainsParameters.powerPhase1 values:{"value":1134.28,"time":"2022-05-31T08:37:32.349Z","from":"system.adapter.mercury.0","q":0,"ack":true} options: null

**Comment by Apollon77** [comment]
And BTW : Which Admin version?

**Comment by Anzic23** [comment]
5.4.9

**Comment by Apollon77** [comment]
I try to workaround ... but seems to be an admin issue :-(

**Comment by Apollon77** [comment]
Please check GitHub version

**Comment by Anzic23** [comment]
> Please check GitHub version

<html>
<body>


host.iobroker | 2022-05-31 12:18:01.812 | info | instance system.adapter.broadlink2.0 started with pid 3093
-- | -- | -- | --
host.iobroker | 2022-05-31 12:18:00.782 | info | Restart adapter system.adapter.broadlink2.0 because enabled
host.iobroker | 2022-05-31 12:18:00.779 | info | instance system.adapter.broadlink2.0 scheduled normal terminated and will be restarted on schedule.
host.iobroker | 2022-05-31 12:17:59.183 | info | Rebuild for adapter system.adapter.influxdb.0 not successful in 3 tries. Adapter will not be restarted again. Please execute "npm install --production" in adapter directory manually.
host.iobroker | 2022-05-31 12:17:59.183 | error | instance system.adapter.influxdb.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
host.iobroker | 2022-05-31 12:17:59.183 | error | Caught by controller[0]: }
host.iobroker | 2022-05-31 12:17:59.182 | error | Caught by controller[0]: requireStack: [ '/opt/iobroker/node_modules/iobroker.influxdb/main.js' ]
host.iobroker | 2022-05-31 12:17:59.182 | error | Caught by controller[0]: code: 'MODULE_NOT_FOUND',
host.iobroker | 2022-05-31 12:17:59.182 | error | Caught by controller[0]: at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:75:12) {
host.iobroker | 2022-05-31 12:17:59.182 | error | Caught by controller[0]: at Function.Module._load (internal/modules/cjs/loader.js:790:12)
host.iobroker | 2022-05-31 12:17:59.181 | error | Caught by controller[0]: at Module.load (internal/modules/cjs/loader.js:950:32)
host.iobroker | 2022-05-31 12:17:59.181 | error | Caught by controller[0]: at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
host.iobroker | 2022-05-31 12:17:59.181 | error | Caught by controller[0]: at Module._compile (internal/modules/cjs/loader.js:1085:14)
host.iobroker | 2022-05-31 12:17:59.181 | error | Caught by controller[0]: at Object.<anonymous> (/opt/iobroker/node_modules/iobroker.influxdb/main.js:16:22)
host.iobroker | 2022-05-31 12:17:59.181 | error | Caught by controller[0]: at require (internal/modules/cjs/helpers.js:101:18)
host.iobroker | 2022-05-31 12:17:59.181 | error | Caught by controller[0]: at Module.require (internal/modules/cjs/loader.js:974:19)
host.iobroker | 2022-05-31 12:17:59.180 | error | Caught by controller[0]: at Function.Module._load (internal/modules/cjs/loader.js:746:27)
host.iobroker | 2022-05-31 12:17:59.180 | error | Caught by controller[0]: at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
host.iobroker | 2022-05-31 12:17:59.180 | error | Caught by controller[0]: - /opt/iobroker/node_modules/iobroker.influxdb/main.js
host.iobroker | 2022-05-31 12:17:59.180 | error | Caught by controller[0]: Require stack:
host.iobroker | 2022-05-31 12:17:59.179 | error | Caught by controller[0]: Error: Cannot find module 'lib/tools.js'
host.iobroker | 2022-05-31 12:17:59.179 | error | Caught by controller[0]: ^
host.iobroker | 2022-05-31 12:17:59.178 | error | Caught by controller[0]: throw err;
host.iobroker | 2022-05-31 12:17:59.178 | error | Caught by controller[0]: internal/modules/cjs/loader.js:905


</body>
</html>

**Comment by Apollon77** [comment]
meh my fails ... try again please

**Comment by Anzic23** [comment]
why does the version from github take sooooo long to install? :((

**Comment by Anzic23** [comment]
sorry, i got to go. I'll check later when I get back.

**Comment by Apollon77** [comment]
This should never happen with InfluxDB ... There are no biunary parts in it. WHat is the full log?

ANd please try again to install from Github, there was a code bug

**Comment by Anzic23** [comment]
![image](https://user-images.githubusercontent.com/37106885/171142147-f7f2fcb0-fc8e-4741-9adf-e1c21ca32db9.png)
I can't stop this process

**Comment by Anzic23** [comment]
> > why does the version from github take sooooo long to install? :((
> 
> Thsi is because of a Bug "in npm 6 and GitHub turning off a feature ... thats why GitHub installs take 10+ mins currently ... out of our control

maybe you should switch to npm 8? I tried for some installations, it seems to work without errors

**Comment by Anzic23** [comment]
![image](https://user-images.githubusercontent.com/37106885/171142933-e5c903d6-ba6d-4646-b86e-69ec21872862.png)
when you click the test connection button

**Comment by Diginix** [comment]
Go to CLI and kill the "git ls-remote" process manually. Then the installation will start and finish within seconds.
Full description of this behavior incl solution: https://github.com/ioBroker/ioBroker.admin/issues/1471

**Comment by Anzic23** [comment]
<html>
<body>


influxdb.0 | 2022-05-31 12:36:19.937 | debug | testConnection msg-object: {"command":"test","message":"{\"config\": {\"dbversion\": \"2.x\", \"protocol\": \"http\", \"port\": \"8086\", \"host\": \"influxdb\", \"user\": \"admin\", \"organization\": \"Anzor\", \"dbname\": \"iobroker/global\", \"requestTimeout\": \"300000\", \"validateSSL\": true, \"password\": \"V\u0002][]\", \"token\": \"bkAy9vDgOU-8X_2pzM_orDnDgli7VArkjOBrOZuE_U0OCNFDYfr6hACKOqczh2jSuMNqH-cFmcEB-lnVnzRczg==\", \"path\": \"\"}}","from":"system.adapter.admin.0","callback":{"message":"{\"config\": {\"dbversion\": \"2.x\", \"protocol\": \"http\", \"port\": \"8086\", \"host\": \"influxdb\", \"user\": \"admin\", \"organization\": \"Anzor\", \"dbname\": \"iobroker/global\", \"requestTimeout\": \"300000\", \"validateSSL\": true, \"password\": \"V\u0002][]\", \"token\": \"bkAy9vDgOU-8X_2pzM_orDnDgli7VArkjOBrOZuE_U0OCNFDYfr6hACKOqczh2jSuMNqH-cFmcEB-lnVnzRczg==\", \"path\": \"\"}}","id":123,"ack":false,"time":1653989779935},"_id":94415987}
-- | -- | -- | --



</body>
</html>

**Comment by Apollon77** [comment]
duplicate https://github.com/ioBroker/ioBroker.admin/issues/1138

**Comment by Anzic23** [comment]
fixed in admin 6

**Comment by Apollon77** [comment]
Yes and no ... more "fixed in latest Influxdb version" :-)

**Comment by Anzic23** [comment]
do not understand what you talking about? :)
![image](https://user-images.githubusercontent.com/37106885/171947323-bfec1c86-c635-4235-8bbe-fcd100384851.png)

**Comment by Apollon77** [comment]
I just tell that the issue was fixed in influxdb 3.1.3 and not Admin 6 :-)) but all fine

**Comment by Apollon77** [comment]
Thank you for your re-verification

**Comment by Anzic23** [comment]
always happy to help :)
